### ISSUE TITLE
Take topicdata() and formatmap() out of the queue

### ISSUE THREAD

**Issue by jpmens** [jpmens/mqttwarn#27]
topic processing and format functions are done in the job queue, i.e. they're invoked N times if a message has N targets.

Pull those up and invoke before the job is added to the queue.

Simultaneously, attempt to parse JSON from payload BEFORE the filter() function is invoked, and pass data{} to it as well. (Doesn't cost more, and adds functionality.) In order to not break existing filter(), add data=None to end of call.

**Comment by jpmens** [comment]
Addressed in #169

**Comment by amotl** [comment]
The first part "_Pull those up and invoke before the job is added to the queue_" in fact is addressed and resolved, that's true. Don't know about the "_attempt to parse JSON from payload BEFORE the filter() function is invoked, and pass data{} to it as well_" part, though, since we're not yet into filtering. Please check.
