### ISSUE TITLE
Zabbix service not working with mqttwarn 0.14.2

### ISSUE THREAD

**Issue by Sass-ctrl** [jpmens/mqttwarn#413]
when I start my mqttwarn on my Ubuntu Server 18.04 I recive data from my sensor BUT I also get an error saying: "Invalid configuration: topic "/blaa/blabla/blablabla" points to non-existing service "zabbix" "

I would be greatfull for some quick response! 

Greetings
Sass

**Comment by Sass-ctrl** [comment]
Edit: If I try to Install the zabbix service via mqttwarn[zabbix] I get the error: "mqttwarn 0.14.2 does not provide the extra zabbix"

**Comment by jpmens** [comment]
> I would be greatfull for some quick response!

Correct your configuration.

**Comment by Sass-ctrl** [comment]
I am quite new to this... Do you have any idea what miss-configuration could cause such a problem? I am kind off lost..
Thanks

**Comment by amotl** [comment]
Dear @Sass-ctrl,

thanks for reporting this.

## Investigation
> Unable to load service "zabbix" from file "zabbix.py": No module named vendor.

The reason is:
https://github.com/jpmens/mqttwarn/blob/0.14.2/mqttwarn/services/zabbix.py#L12

This is my fault. I didn't touch the Zabbix service when revamping mqttwarn the other day. But at least, I've put two notes about it into the backlog.

## Goals for 0.15.0
- Refactor `examples/zabbix/zabbix_mqtt_agent.py`
- Refactor `vendor/ZabbixSender.py`

-- https://github.com/jpmens/mqttwarn/blob/0.14.2/doc/backlog.rst#goals-for-0150

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear @Sass-ctrl,

I've just made some adjustments and released mqttwarn 0.15.0. While I haven't exactly tested the Zabbix service beforehand, I will be happy to hear about the outcome for you.

With kind regards,
Andreas.

**Comment by Sass-ctrl** [comment]
Hey Andreas,

 

It is working great now! There is just one thing I have a question about. when starting mqttwarn I do get one more "warining" that says "cannot decode JSON object, payload=32.291 <-- (my sensor data):'float' object is not iterable"

 

In what way do I have to transform my data to get rid of that warning? 

 

Thanks a lot and greetings

Luca

 

Gesendet: Dienstag, 14. April 2020 um 01:14 Uhr
Von: "Andreas Motl" <notifications@github.com>
An: "jpmens/mqttwarn" <mqttwarn@noreply.github.com>
Cc: "LSonnenfroh" <luca.sonnenfroh@gmx.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [jpmens/mqttwarn] Zabbix service not working with mqttwarn 0.14.2 (#413)


 

Dear @Sass-ctrl,

I've just made some adjustments and released mqttwarn 0.15.0. While I haven't exactly tested the Zabbix service beforehand, I will be happy to hear about the outcome for you.

With kind regards,
Andreas.

**Comment by jpmens** [comment]
The warning is simply informing you that the payload isn't JSON; you will get it nevertheless. The reason is, we try to decode JSON and warn if that's not possible. By setting log level to INFO you would get rid of the warnings in the log. Alternatively you could send your data as JSON, say

```json
{"value":32.291}
```

Closing as solved.
