### ISSUE TITLE
Docker image contains stale mqttwarn package

### ISSUE THREAD

**Issue by amotl** [jpmens/mqttwarn#495]
@tg44 reported at #473 about wrong output of `mqttwarn --version` when using the Docker image:

> If you invoke `docker run -it --rm jpmens/mqttwarn:0.20.0 mqttwarn --version`, you will get back 0.16.0.

**Comment by amotl** [comment]
I can confirm that. However I have no idea how this could even happen?

**Comment by tg44** [comment]
I wrote down the root of the prolem. It is bcs installing a tool in a docker image is antipattern, and will result unwanted cachehit.

Docker images are build from layers. Every line in the dockerfile references an other image or a command, every line will result a new image layer. When docker builds an image, it tries to look up already created layers if this is possible. Because you install the tool via pip, the docker commands are all cacheable. If you add files to a container, it will break the caches.

## Demonstration
```
# initial steps
echo FROM curlimages/curl:latest > testDockerFile
echo RUN curl github.com >> testDockerFile

# first run
docker build . -f testDockerFile -t docker-build-test

# second run
docker build . -f testDockerFile -t docker-build-test

# adding a file and new steps
touch test.file
echo COPY ./test.file /app/test.file >> testDockerFile
echo RUN curl google.com >> testDockerFile

# third run
docker build . -f testDockerFile -t docker-build-test

# forth run
docker build . -f testDockerFile -t docker-build-test

# modify the file
echo asd > test.file

# fifth run
docker build . -f testDockerFile -t docker-build-test

# cleanup
rm test.file
rm testDockerFile
docker image rm docker-build-test
```
### First run
We will download the curl image (as layer 1), and call github.com (as later 2).

### Second run
We reuse both layers from cache, call nothing.

### Third run
We reuse layer 1 and 2, but now we have new stages as adding a file (3) and calling curl again (4) so we will do those

### Forth run
The file hash in L3 is the same as before, so we get L1-4 from cache, call nothing.

### Fifth run
The file hash is different so we do again L3 and L4, resulting a new curl call in L4.

**Comment by amotl** [comment]
Dear Gergő,

> I wrote down the root of the prolem. It is bcs installing a tool in a docker image is antipattern, and will result unwanted cachehit.

Thanks a stack for being persistent on this. Now I totally get your point!

With kind regards,
Andreas.

**Comment by amotl** [comment]
I believe it works now. After minting the latest release, we now see:
```shell
$ docker run -it --rm jpmens/mqttwarn:0.23.0 mqttwarn --version
mqttwarn 0.23.0
```

Thank you again!
