### ISSUE TITLE
Dealing with multiple messages

### ISSUE THREAD

**Issue by egraaf** [jpmens/mqttwarn#51]
I was wondering how to handle dealing with several messages at the same time, or remember state when I was thinking about logging the time it took for my daily commute to work and back.

I would use owntracker to detect the timestamp when I leave location home, and then later with a new message the timestamp when I enter location work.

I would need something like:

If leave home, remember timestamp as LEFTHOME (perhaps publish as a message /commute/towork/leavingtimestamp)
if arrive at work, subtract LEFTHOME from ARRIVEWORK and publish as /commute/towork/duration

It seems mqttwarn only deals with a single message at a time, and perhaps that is its purpose, so I wonder if there is a way to do the above scenario?

Thank you very much for the work you put into mqttwarn.

(I was able to solve my earlier issue with a filter by the way, I ended up with the following filter:

def OwntracksFilter(topic, message):
    data = dict(json.loads(message).items())
    if 'desc' in data and 'event' in data:
        if data['desc'] == "Werk" and data['event'] == "leave":
            return False
    return True

**Comment by marcelrv** [comment]
not sure if it macthed your usecase, but in the thinkspeak service I added a build=true/false
In case it is true, it will wait for the next message to arrive so it can combine info in 1 submission. 
https://github.com/jpmens/mqttwarn/blob/master/services/thingspeak.py#L34

(note in case of thingspeak the submission rate is limited, hence collecting all parameters to send in one go instead of sending them individually was triggering this functionality)
