### ISSUE TITLE
SMTP service croaks with KeyError: 'username'

### ISSUE THREAD

**Issue by amotl** [jpmens/mqttwarn#573]
Dear @symonjim,

thanks for your report at https://github.com/jpmens/mqttwarn/issues/571#issuecomment-1219591379 about that error:
```
2022-08-18 10:45:37,056 ERROR    [mqttwarn.core             ] Cannot invoke service for `smtp'
Traceback (most recent call last):
  File "d:\program files (d)\python37\lib\site-packages\mqttwarn\core.py", line 517, in processor
    notified = timeout(module.plugin, (srv, st))
  File "d:\program files (d)\python37\lib\site-packages\mqttwarn\util.py", line 133, in timeout
    raise it.exception
  File "d:\program files (d)\python37\lib\site-packages\mqttwarn\util.py", line 121, in run
    self.result = func(*args, **kwargs)
  File "d:\program files (d)\python37\lib\site-packages\mqttwarn\services\smtp.py", line 24, in plugin
    username    = item.config['username']
KeyError: 'username'
```

With kind regards,
Andreas.

**Comment by amotl** [comment]
For the SMTP service plugin, all parameters `server`, `sender`, `starttls`, `username`, and `password`, are required.

https://github.com/jpmens/mqttwarn/blob/871a381f0793b3e086609ea55fb248c6be10743b/mqttwarn/services/smtp.py#L21-L25 

However, if you don't want to invoke SMTP AUTH against your SMTP server, you can configure `username` to use a falsey value, for example `None`. The same holds true for the `starttls` parameter.

https://github.com/jpmens/mqttwarn/blob/871a381f0793b3e086609ea55fb248c6be10743b/mqttwarn/services/smtp.py#L48-L51

I hope this helps.

**Comment by amotl** [comment]
@jpmens: We could improve the configuration convenience at this spot by making the optional parameters optional, like:
```
 starttls    = item.config.get('starttls')
 username    = item.config.get('username')
 password    = item.config.get('password')
```

What do you think about it?

**Comment by jpmens** [comment]
That sounds good to me, @amotl

**Comment by symonjim** [comment]
It successfully loaded the smtp service and it appears that by including all the parameters it is sending the email but now it says the target machine is actively refusing it. I'm wondering whether my firewall maybe doesn't like it. Any idea what I could list as an exception to let through the protection? Maybe mqttwarn? Something about where the message is coming from?

The other thing it may be is what I am using for username. I seem to have various usernames floating around. I'm currently trying none but there is also the name label in the smtp Targets list and sender. I have a lot of combinations to try.

2022-08-18 16:47:54,227 DEBUG    [mqttwarn.core             ] Processor #0 is handling: `smtp' for Jim Symon
2022-08-18 16:47:54,228 INFO     [mqttwarn.core             ] Invoking service plugin for `smtp'
2022-08-18 16:47:54,228 DEBUG    [mqttwarn.services.smtp    ] *** MODULE=d:\program files (d)\python37\lib\site-packages\mqttwarn\services\smtp.py: service=smtp, target=Jim Symon
2022-08-18 16:47:54,228 DEBUG    [mqttwarn.services.smtp    ] Sending SMTP notification to Jim Symon, addresses: ['symonjim@sybr.net']
2022-08-18 16:47:58,326 WARNING  [mqttwarn.services.smtp    ] Error sending notification to SMTP recipient Jim Symon, addresses: ['symonjim@sybr.net']. Exception: [WinError 10061] No connection could be made because the target machine actively refused it
2022-08-18 16:47:58,327 WARNING  [mqttwarn.core             ] Notification of smtp for `IOTgadgettopic' FAILED or TIMED OUT

**Comment by amotl** [comment]
Dear Jim,

in order to give specific advice to make SMTP submission to your mailserver work, which is probably not really feasible for us, we would need to know about your environment and which (kind of) SMTP server you are trying to address here.

> I'm wondering whether my firewall maybe doesn't like it. Any idea what I could list as an exception to let through the protection?

There are many possibilities where things might go south. Let me enumerate two of them:

1. In general, for submitting email, you will usually have to authenticate with your SMTP server and use encryption so that the password is not transferred in plaintext.
2. Many providers or carriers don't allow user traffic on port 25, either blocking it on the network already, or not allowing SMTP mail to be submitted on port 25. You might want to try port 587, which is the default port for SMTP submission on the modern web.

With kind regards,
Andreas.

**Comment by amotl** [comment]
> The other thing it may be is what I am using for username. I seem to have various usernames floating around. I'm currently trying none but there is also the name label in the smtp Targets list and sender. I have a lot of combinations to try.

You definitively should make sure to use the right credentials. Please be aware that providers may block your account temporarily after a number of failed login attempts. If you are using your personal credentials, you may want to look them up in your mail program, or maybe just create new ones.

**Comment by amotl** [comment]
Dear Jim,

with 1f147a35, we improved the situation when aiming to use the SMTP service plugin to submit email to a server without authentication, effectively making the `username` and `password` parameters optional.

Unfortunately, we can not help finding the right credentials to use in your case, so I believe it is safe to close this issue.

With kind regards,
Andreas.

P.S.: We are very happy about your reports, as they improved both code as well as documentation (#571). Don't hesitate to ask for further support when discovering other flaws with `mqttwarn`, especially on Windows.
