### ISSUE TITLE
watchdog timer in mqttwarn?

### ISSUE THREAD

**Issue by vielmetti** [jpmens/mqttwarn#78]
Is it possible to configure mqttwarn to behave as a watchdog timer, e.g. to send out an alert if something doesn't happen?

The example use case is a device that emits to a channel device-id/# and the rule would be something like "if you don't hear any messages on device-id/# for 15 minutes, do this".

If not, then consider this an enhancement request....

**Comment by fab33** [comment]
It would be fine to implement this function.
I have an arduino sending mqtt data from CT sensors via ESP8266. Then mqttwarn send topics to emoncms instance. But I want to configure email or pushbullet alert if topics wasn't updated since 10 minutes. Can you explain me haw can i do it via python and cron ?
Thank you.

**Comment by amotl** [comment]
Hey @vielmetti, @dgomes and @fab33! We did this per #194 based on the cron feature as suggested by @jpmens. We use it in production and it works perfectly for us.
